In [1]:
import pandas as pd

In [3]:
orders = pd.read_csv("orders.csv", encoding="utf-8-sig")
order_items = pd.read_csv("order_items.csv", encoding="utf-8-sig")
products = pd.read_csv("products.csv", encoding="utf-8-sig")
suppliers = pd.read_csv("suppliers.csv", encoding="utf-8-sig")
returns = pd.read_csv("returns.csv", encoding="utf-8-sig")
users = pd.read_csv("users.csv", encoding="utf-8-sig")

In [18]:
# Merging order_items table with products table
df = order_items.merge(products, on="product_id", how="left", validate="many_to_one")

In [19]:
df.head()

,order_id,product_id,quantity,unit_price,total_price,product_name,category,supplier_id,retail_price
0,1,17,2,415.55,831.10,PlayStation,Electronics,42,415.55
1,1,25,1,361.41,361.41,Trackpants,Sports,26,361.41
2,1,14,3,68.47,205.41,Vacuum cleaner,Electronics,39,68.47
3,2,2,3,215.84,647.52,Dining table,Home,10,215.84
4,2,24,4,471.33,1885.32,Sneakers,Sports,46,471.33

In [20]:
# Adding supplier info from supplier table in df
df = df.merge(suppliers, on="supplier_id", how="left", validate="many_to_one")

In [21]:
df.head()

,order_id,product_id,quantity,unit_price,total_price,product_name,category,supplier_id,retail_price,supplier_name,country
0,1,17,2,415.55,831.10,PlayStation,Electronics,42,415.55,Blackstone Distribution,Brazil
1,1,25,1,361.41,361.41,Trackpants,Sports,26,361.41,Kingsley Trading,UK
2,1,14,3,68.47,205.41,Vacuum cleaner,Electronics,39,68.47,Heritage Trading Co,Canada
3,2,2,3,215.84,647.52,Dining table,Home,10,215.84,Cascade Supply Co,Canada
4,2,24,4,471.33,1885.32,Sneakers,Sports,46,471.33,Greenfield Supply Co,Canada

In [23]:
# Adding order info from orders table in df
df = df.merge(orders, on="order_id", how="left", validate="many_to_one")

In [24]:
df.head()

,order_id,product_id,quantity,unit_price,total_price,product_name,category,supplier_id,retail_price,supplier_name,country,user_id,order_date,status
0,1,17,2,415.55,831.10,PlayStation,Electronics,42,415.55,Blackstone Distribution,Brazil,4362,2020-01-01 00:00:00,Completed
1,1,25,1,361.41,361.41,Trackpants,Sports,26,361.41,Kingsley Trading,UK,4362,2020-01-01 00:00:00,Completed
2,1,14,3,68.47,205.41,Vacuum cleaner,Electronics,39,68.47,Heritage Trading Co,Canada,4362,2020-01-01 00:00:00,Completed
3,2,2,3,215.84,647.52,Dining table,Home,10,215.84,Cascade Supply Co,Canada,5534,2020-01-01 01:00:00,Completed
4,2,24,4,471.33,1885.32,Sneakers,Sports,46,471.33,Greenfield Supply Co,Canada,5534,2020-01-01 01:00:00,Completed

In [25]:
# Adding user info from users table in df
df = df.merge(users, on="user_id", how="left", validate="many_to_one")

In [26]:
df.head()

,order_id,product_id,quantity,unit_price,total_price,product_name,category,supplier_id,retail_price,supplier_name,country_x,user_id,order_date,status,name,age,gender,country_y,signup_date
0,1,17,2,415.55,831.10,PlayStation,Electronics,42,415.55,Blackstone Distribution,Brazil,4362,2020-01-01 00:00:00,Completed,Kay Jones,20,Female,US,2029-12-10
1,1,25,1,361.41,361.41,Trackpants,Sports,26,361.41,Kingsley Trading,UK,4362,2020-01-01 00:00:00,Completed,Kay Jones,20,Female,US,2029-12-10
2,1,14,3,68.47,205.41,Vacuum cleaner,Electronics,39,68.47,Heritage Trading Co,Canada,4362,2020-01-01 00:00:00,Completed,Kay Jones,20,Female,US,2029-12-10
3,2,2,3,215.84,647.52,Dining table,Home,10,215.84,Cascade Supply Co,Canada,5534,2020-01-01 01:00:00,Completed,Fae Caprio,49,Female,UK,2033-02-24
4,2,24,4,471.33,1885.32,Sneakers,Sports,46,471.33,Greenfield Supply Co,Canada,5534,2020-01-01 01:00:00,Completed,Fae Caprio,49,Female,UK,2033-02-24

In [27]:
print(df.columns.tolist())

['order_id', 'product_id', 'quantity', 'unit_price', 'total_price', 'product_name', 'category', 'supplier_id', 'retail_price', 'supplier_name', 'country_x', 'user_id', 'order_date', 'status', 'name', 'age', 'gender', 'country_y', 'signup_date']

In [28]:
# Add returns info
df = df.merge(returns[['order_id','return_reason','refund_amount']], on="order_id", how="left", validate="many_to_one")

In [29]:
print(df.columns.tolist())

['order_id', 'product_id', 'quantity', 'unit_price', 'total_price', 'product_name', 'category', 'supplier_id', 'retail_price', 'supplier_name', 'country_x', 'user_id', 'order_date', 'status', 'name', 'age', 'gender', 'country_y', 'signup_date', 'return_reason', 'refund_amount']

In [30]:
# Create target variable
df['Returned'] = df['return_reason'].notnull().astype(int)

In [31]:
df.head()

,order_id,product_id,quantity,unit_price,total_price,product_name,category,supplier_id,retail_price,supplier_name,...,order_date,status,name,age,gender,country_y,signup_date,return_reason,refund_amount,Returned
0,1,17,2,415.55,831.10,PlayStation,Electronics,42,415.55,Blackstone Distribution,...,2020-01-01 00:00:00,Completed,Kay Jones,20,Female,US,2029-12-10,NaN,NaN,0
1,1,25,1,361.41,361.41,Trackpants,Sports,26,361.41,Kingsley Trading,...,2020-01-01 00:00:00,Completed,Kay Jones,20,Female,US,2029-12-10,NaN,NaN,0
2,1,14,3,68.47,205.41,Vacuum cleaner,Electronics,39,68.47,Heritage Trading Co,...,2020-01-01 00:00:00,Completed,Kay Jones,20,Female,US,2029-12-10,NaN,NaN,0
3,2,2,3,215.84,647.52,Dining table,Home,10,215.84,Cascade Supply Co,...,2020-01-01 01:00:00,Completed,Fae Caprio,49,Female,UK,2033-02-24,NaN,NaN,0
4,2,24,4,471.33,1885.32,Sneakers,Sports,46,471.33,Greenfield Supply Co,...,2020-01-01 01:00:00,Completed,Fae Caprio,49,Female,UK,2033-02-24,NaN,NaN,0

In [33]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

In [35]:
df['category_code'] = df['category'].astype('category').cat.codes

In [36]:
df['supplier_country_code'] = (df['country_x'].astype('category').cat.codes)

In [38]:
features = ['category_code','supplier_country_code','retail_price','quantity']
X = df[features]
y = df['Returned']

In [39]:
print(X.isnull().sum())

category_code            0
supplier_country_code    0
retail_price             0
quantity                 0
dtype: int64

In [46]:
y_pred = model.predict(X_test)
print("Actual classes:")
print(y_test.value_counts())
print("\nPredicted classes:")
print(pd.Series(y_pred).value_counts())

Actual classes:
Returned
0    17220
1     1950
Name: count, dtype: int64

Predicted classes:
1    10158
0     9012
Name: count, dtype: int64

In [47]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

In [48]:
model = LogisticRegression(max_iter=500, class_weight="balanced", random_state=42)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

In [49]:
print(classification_report(y_test, y_pred, zero_division=0))

              precision    recall  f1-score   support

           0       0.90      0.47      0.62     17220
           1       0.10      0.52      0.17      1950

    accuracy                           0.47     19170
   macro avg       0.50      0.50      0.39     19170
weighted avg       0.82      0.47      0.57     19170

In [53]:
from sklearn.preprocessing import LabelEncoder

In [55]:
# Encode categorical features
df['category_code'] = LabelEncoder().fit_transform(df['category'].astype(str))
df['supplier_country_code'] = LabelEncoder().fit_transform(df['country_y'].astype(str))

In [56]:
features = ['category_code','supplier_country_code','retail_price','quantity']
X = df[features]
y = df['Returned']

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

model = LogisticRegression(max_iter=500)
model.fit(X_train, y_train)

LogisticRegression(max_iter=500)

In [57]:
# Predict probabilities for the whole dataset
df['return_probability'] = model.predict_proba(X)[:,1]

In [61]:
import pandas as pd
from pathlib import Path

# Use the same features and feature order used to train the model
features = [
    "category_code",
    "supplier_country_code",
    "retail_price",
    "quantity"
]

# Confirm all required feature columns exist
missing_features = [col for col in features if col not in df.columns]

if missing_features:
    raise ValueError(
        f"Missing feature columns: {missing_features}. "
        "Create these columns before generating predictions."
    )

# Build the full feature matrix: one prediction per df row
X_all = df[features]

# Check for missing values that would prevent valid predictions
print("Missing values in model features:")
print(X_all.isnull().sum())

# Find the probability column that represents Returned = 1
positive_class_index = list(model.classes_).index(1)

# Add the model's predicted probability of return to every row
df = df.copy()

df["return_probability"] = model.predict_proba(X_all)[:, positive_class_index]

# Inspect probabilities before filtering
print("\nReturn-probability summary:")
print(df["return_probability"].describe())

print("\nRows with probability > 0.60:")
print((df["return_probability"] > 0.60).sum())

Missing values in model features:
category_code            0
supplier_country_code    0
retail_price             0
quantity                 0
dtype: int64

Return-probability summary:
count    63900.000000
mean         0.101992
std          0.003086
min          0.094602
25%          0.099768
50%          0.102067
75%          0.104210
max          0.109810
Name: return_probability, dtype: float64

Rows with probability > 0.60:
0

In [62]:
high_risk = df[df['return_probability'] > 0.5]
high_risk_products = high_risk[['product_id','product_name','category','supplier_name','return_probability']]

In [63]:
# Export
high_risk_products.to_csv("high_risk_products.csv", encoding="utf-8-sig", index=False)

In [60]:
print(df['return_probability'].describe())
print(df['return_probability'].value_counts(bins=[0,0.2,0.4,0.6,0.8,1]))

count    63900.000000
mean         0.101992
std          0.003086
min          0.094602
25%          0.099768
50%          0.102067
75%          0.104210
max          0.109810
Name: return_probability, dtype: float64
(-0.001, 0.2]    63900
(0.2, 0.4]           0
(0.4, 0.6]           0
(0.6, 0.8]           0
(0.8, 1.0]           0
Name: count, dtype: int64

In [65]:
# One risk score per product: average probability across its order-item rows
product_risk = (
    df.groupby(
        ["product_id", "product_name", "category", "supplier_name"],
        as_index=False
    )["return_probability"]
    .mean()
    .sort_values("return_probability", ascending=False)
)

top_10_percent_threshold = product_risk["return_probability"].quantile(0.90)

high_risk_products = product_risk[
    product_risk["return_probability"] >= top_10_percent_threshold
].copy()

# Save to the original CSV-data folder
output_path = Path(
    r"C:\Disk Partition\datax-labs\Project Phase\Phase 1.2\Synthetic data"
) / "high_risk_products.csv"

high_risk_products.to_csv(
    output_path,
    encoding="utf-8-sig",
    index=False
)

print(f"\nSaved file: {output_path}")
print(f"High-risk products exported: {len(high_risk_products)}")
print(high_risk_products.head(10))

Saved file: C:\Disk Partition\datax-labs\Project Phase\Phase 1.2\Synthetic data\high_risk_products.csv
High-risk products exported: 3
   product_id product_name category         supplier_name  return_probability
6           7      Handbag   Beauty    Parkside Wholesale            0.106406
9          10      Perfume   Beauty  White Rock Merchants            0.105123
7           8     Lipstick   Beauty    Granite Peak Goods            0.105105